config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/top'
  end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    get 'saunas_bookmarks' => 'bookmarks#show'
    resources :posts
    resources :post_comments, only: [:create, :destroy]
    resources :saunas, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
    resources :customers, only: [:index,:show,:edit,:create,:update] do
      member do
        get :confirm
        patch :withdraw
      end
    end
  end

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :saunas
    resources :customers, except: [:new,:create,:destroy]
    resources :posts, only: [:index,:show,:edit,:update] do
      member do
        get :customer
        patch :withdraw
      end

      patch "hide/:comment_id" => "post_comments#hide", as: 'hide'
      patch "display/:comment_id" => "post_comments#display", as: 'display'
    end
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sauna.rb
class Sauna < ApplicationRecord
  #has_many :tag, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one_attached :image


  validates :sauna_name, presence: true
  validates :image, presence: true
  validates :sauna_temperature, presence: true
  validates :water_temperature, presence: true
  validates :access, presence: true
  validates :introduction, presence: true

  def bookmarked_by?(customer)
    bookmarks.where(customer_id: customer).exists?
  end

  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  def self.looks(word, prefecture, search)

    if search == "perfect_match"
      if prefecture.blank?
        @sauna = Sauna.where("sauna_name LIKE?","#{word}")
      else
        @sauna = Sauna.where("sauna_name LIKE?","#{word}").where(prefecture:  Sauna.prefectures.key(prefecture.to_i))
      end
    elsif search == "forward_match"
      if prefecture.blank?
        @sauna = Sauna.where("sauna_name LIKE?","#{word}%")
      else
        @sauna = Sauna.where("sauna_name LIKE?","#{word}%").where(prefecture:  Sauna.prefectures.key(prefecture.to_i))
      end
    elsif search == "backward_match"
      if prefecture.blank?
        @sauna = Sauna.where("sauna_name LIKE?","%#{word}")
      else
        @sauna = Sauna.where("sauna_name LIKE?","%#{word}").where(prefecture:  Sauna.prefectures.key(prefecture.to_i))
      end
    elsif search == "partial_match"
      if prefecture.blank?
        @sauna = Sauna.where("sauna_name LIKE?","%#{word}%")
      else
        @sauna = Sauna.where("sauna_name LIKE?","%#{word}%").where(prefecture:  Sauna.prefectures.key(prefecture.to_i))
      end
    else
        @sauna = Sauna.all
    end

  end
end

app/controllers/admin/saunas_controller.rb
class Admin::SaunasController < ApplicationController
  before_action :authenticate_admin!

  def index
    @saunas = Sauna.all.page(params[:page]).per(8) #8項目毎にページネート
    @sauna = Sauna.new
  end

  def new
    @sauna = Sauna.new
  end

  def create
    @sauna = Sauna.new(sauna_params)
    @sauna.save!
    redirect_to admin_sauna_path(@sauna.id)
  end

  def show
    @sauna = Sauna.find(params[:id])
    @sauna_new = Sauna.new
  end

  def edit
    @sauna = Sauna.find(params[:id])
  end

  def update
    @sauna = Sauna.find(params[:id])
    @sauna.update(sauna_params)
    redirect_to admin_sauna_path(@sauna)
  end

  private

  def sauna_params
    params.require(:sauna).permit(:tag_id, :sauna_name, :image, :sauna_temperature, :water_temperature, :access, :phone_number, :introduction, :is_active, :prefecture).merge(prefecture: params[:sauna][:prefecture].to_i)
  end

end

app/helpers/admin/saunas_helper.rb
module Admin::SaunasHelper
end

app/views/admin/saunas/edit.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">
    <div class="col-md-2"></div>
    <h4 class="col-md-2 mx-auto text-center">
      <strong>サウナ編集</strong>
    </h4>
    <div class="col-md-8"></div>
  </div>
  <div class="m-md-2"><br></div>

    <%= form_with model: @sauna, url: admin_sauna_path(@sauna) do |f| %>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">都道府県</div>
      <div class="col-md-8"><%= f.select :prefecture,  options_for_select(Sauna.prefectures), {prompt: "選択してください"}, class: "prefecture-select" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :image, '店舗画像' %></div>
      <div class="col-md-8"><%= f.file_field :image, accept: "image/*", required: true %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :sauna_name, '店舗名' %></div>
      <div class="col-md-8"><%= f.text_field :sauna_name, placeholder: "店舗名", required: true, size: "44" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :access, 'アクセス' %></div>
      <div class="col-md-8"><%= f.text_field :access, placeholder: "ここにアクセスを記述します", required: true, size: "44" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :introduction, '紹介文' %></div>
      <div class="col-md-8"><%= f.text_area :introduction, placeholder: "ここに紹介文を記述します", required: true, size: "46x10" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :sauna_temperature, 'サウナ温度' %></div>
      <div class="col-md-8"><%= f.text_field :sauna_temperature, placeholder: "サウナ温を記入", required: true, size: "44" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :water_temperature, '水風呂温度' %></div>
      <div class="col-md-8"><%= f.text_field :water_temperature, placeholder: "水風呂温度を記入", required: true, size: "44" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">表示ステータス</div>
      <div class="col-md-8">
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, '表示中' %>

      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, '非表示中' %>
      </div>
    </div>

    <div class="row">
      <div class="action center-block mx-auto">
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>

    <% end %>
    </div>


</div>

app/views/admin/saunas/index.html.erb
<div class="container">
  <div class="m-md-2"><br>
  <div class="row">
    <h4 class="col-md-2 mx-auto text-center" style="background-color:#DDD">
      <strong>サウナ一覧</strong>
    </h4>
    <div class="col-md-5 mx-auto text-right">
      <%= link_to "+", new_admin_sauna_path, class: 'btn btn-outline-secondary rounded-circle p-0　box-shadow' %>
    </div>
  </div>

  <diV class="m-md-2"><br></diV>

  <div class="row">

    <div class="col-md-1 mx-auto text-left">
      <strong>サウナID</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>店舗名</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>紹介文</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>アクセス</strong>
    </div>
    <div class="col-md-1 mx-auto text-left">
      <strong>サウナ温度</strong>
    </div>
    <div class="col-md-1 mx-auto text-left">
      <strong>水風呂温度</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>ステータス</strong>
    </div>
  </div>

  <% @saunas.each do |sauna| %>

  <diV class="m-md-1"><br></diV>
  <div class="row">

    <div class="col-md-1 mx-auto text-left"><%= sauna.id %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-2 mx-auto text-left"><%= link_to sauna.sauna_name, admin_sauna_path(sauna.id) %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-2 mx-auto text-left"><%= sauna.introduction%>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-2 mx-auto text-left"><%= sauna.access %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-1 mx-auto text-left"><%= sauna.sauna_temperature %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-1 mx-auto text-left"><%= sauna.water_temperature %>
      <div class="col-md-1"><br></div>
    </div>
    <% if sauna.is_active == true %>
      <div class="col-md-2 mx-auto text-left text-success">
        <strong><%= '表示中' %></strong>
      </div>
    <% else %>
      <div class="col-md-2 mx-auto text-left text-secondary">
        <strong><%= '非表示中' %></strong>
      </div>
    <% end %>
  </div>
  <% end %>

  <!--ページネーション追加-->
  <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2 mx-auto text-left">
      <%= paginate @saunas %>
    </div>
    <div class="col-md-5"></div>
  </div>
</div>
</div>

app/views/admin/saunas/new.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">
    <div class="col-md-2"></div>
    <h4 class="col-md-2 mx-auto text-center">
      <strong>サウナ新規登録</strong>
    </h4>

    <div class="col-md-8"></div>
  </div>

  <div class="m-md-2"><br></div>

  <%= form_with model: @sauna, url: admin_saunas_path do |f| %>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">都道府県</div>
      <div class="col-md-8"><%= f.select :prefecture,  options_for_select(Sauna.prefectures), {prompt: "選択してください"}, class: "prefecture-select" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :image, '店舗画像' %></div>
      <div class="col-md-8"><%= f.file_field :image, accept: "image/*", required: true %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :sauna_name, '店舗名' %></div>
      <div class="col-md-8"><%= f.text_field :sauna_name, placeholder: "店舗名", required: true, size: "44" %></div>
    </div>


    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :access, 'アクセス' %></div>
      <div class="col-md-8"><%= f.text_field :access, placeholder: "ここにアクセスを記述します", required: true, size: "44" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :introduction, '紹介文' %></div>
      <div class="col-md-8"><%= f.text_area :introduction, placeholder: "ここに紹介文を記述します", required: true, size: "46x10" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :sauna_temperature, 'サウナ温度' %></div>
      <div class="col-md-8"><%= f.text_field :sauna_temperature, placeholder: "サウナ温を記入", required: true, size: "44" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :water_temperature, '水風呂温度' %></div>
      <div class="col-md-8"><%= f.text_field :water_temperature, placeholder: "水風呂温度を記入", required: true, size: "44" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-2 text-left">ステータス</div>
    <div class="col-md-7">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '表示中' %>

        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '非表示中' %>
      </div>
    </div>



    <div class="row">
      <div class="action center-block mx-auto">
      <%= f.submit '新規登録', class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/saunas/show.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">
    <div class="col-md-2"></div>
    <h4 class="col-md-2 mx-auto text-center">
      <strong>サウナ詳細</strong>
    </h4>

    <div class="col-md-8"></div>
  </div>

  <div class="m-md-2"><br></div>

    <div class="row">
      <div class="col-md-5 mx-auto">
        <%= image_tag @sauna.image, size:'400x300' %>
    </div>
    <div class="col-md-7 mx-auto">
      <table class="information">

        <tr>
          <th>都道府県</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @sauna.prefecture %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>店舗名</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @sauna.sauna_name %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>商品説明</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @sauna.introduction %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>アクセス</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @sauna.access %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>サウナ温度</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @sauna.sauna_temperature %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>水風呂温度</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @sauna.water_temperature %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>表示ステータス</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <% if @sauna.is_active == true %>
            <td class="text-success">
              <strong><%= '表示中' %></strong>
            </td>
          <% else %>
            <td class="text-secondary">
              <strong><%= '非表示中' %></strong>
            </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>

  <div class="m-md-1"><br></div>


  <div class="row">
    <div class="action center-block mx-auto">
      <%= link_to '編集する',edit_admin_sauna_path(@sauna), class: 'btn btn-success' %>
    </div>
  </div>
</div>