config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/top'
  end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    get 'saunas_bookmarks' => 'bookmarks#show'
    resources :posts
    resources :post_comments, only: [:create, :destroy]
    resources :saunas, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
    resources :customers, only: [:index,:show,:edit,:create,:update] do
      member do
        get :confirm
        patch :withdraw
      end
    end
  end

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :saunas
    resources :customers, except: [:new,:create,:destroy]
    resources :posts, only: [:index,:show,:edit,:update] do
      member do
        get :customer
        patch :withdraw
      end

      patch "hide/:comment_id" => "post_comments#hide", as: 'hide'
      patch "display/:comment_id" => "post_comments#display", as: 'display'
    end
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_comments, dependent: :destroy
  belongs_to :customer
  belongs_to :sauna


  validates :title, presence: true
  validates :body, presence: true

  scope :rate_count, -> {order(rate: :desc)}
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.all.page(params[:page]).per(6)
  end

  def new
    @post = Post.new
    @sauna = Sauna.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = PostComment.where(post_id: params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
   @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post.id), notice: "You have updated user successfully."
    else
      redirect_to request.referer
    end
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    @post.is_deleted = false
    @post.favorite = 3
    if @post.save
      redirect_to post_path(@post)
    else
      @posts = Post.all
      render "index"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :sauna_id, :is_deleted, :rate)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_from.html.erb
<% posts.each do |post| %>
    <div class="col-4">
      <div class="card m-1">
        <div class="card-header">
          <div class="mb-1 text-nowrap overflow-hidden text-truncate"><%= post.sauna.prefecture %></div>
          <div class="mb-1 text-nowrap overflow-hidden text-truncate"><i class="fas fa-store"></i> <%= link_to admin_sauna_path(post.sauna.id) do %><%= post.sauna.sauna_name %><% end %></div>
        </div>
        <%= link_to posts_path(post.id) do %>
        <%= link_to admin_post_path(post.id) do %>
          <%= image_tag post.sauna.image, size: '200x200', class:"card-img-top" %>
        <% end %>
        <div class="card-body">
          <div class="card-text">
          <div class="mb-1"><%= render "admin/posts/static_rate", post: post %></div>
          <div class="mb-1 text-nowrap overflow-hidden text-truncate"><i class="fas fa-user-alt"></i> <%= link_to admin_customer_path(post.customer.id) do %><%= post.customer.name %><% end %></div>
          <div class="mb-1 text-nowrap overflow-hidden text-truncate">タイトル:<%= post.title %></div>
          <div class="mb-1 text-nowrap overflow-hidden text-truncate">レビュー:<%= post.body %></div>
          <div class="mb-1 text-nowrap overflow-hidden text-truncate">
          <% if post.is_deleted == false %>
          <div class="text-success" >
            <%= '表示中' %>
          </div>
          <% else %>
            <div class="text-secondary" >
              <%= '非表示中' %>
            </div>
          <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/posts/_static_rate.html.erb
<div id="rate_<%= post.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
    let raty_<%= post.id %> = document.querySelector('#rate_<%= post.id %>');
    rate_<%= post.id %>.innerHTML = ""
    let option_<%= post.id %> = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        score: "<%= post.rate %>",
        readOnly: true,
      };
    raty(raty_<%= post.id %> ,option_<%= post.id %>);
});
</script>

app/views/admin/posts/edit.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">
    <div class="col-md-2"></div>
    <h4 class="col-md-2 mx-auto text-center">
      <strong>投稿</strong>
    </h4>

    <div class="col-md-8"></div>
  </div>

  <div class="m-md-2"><br></div>


  <%= form_for(@post, url: {controller: 'admin/posts', action: 'update'}) do |f| %>

    <div class="form_group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">投稿者</div>
      <div class="col-md-8"><%= link_to admin_customer_path(@post.customer.id) do %><%= @post.customer.name %><% end %></div>
    </div>

    <div class="m-2"></div>

    <div class="form_group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">都道府県</div>
      <div class="col-md-8"><%= @post.sauna.prefecture %></div>
    </div>

    <div class="m-2"></div>

    <% if params[:id].present? %>
      <div class="form_group row">
        <div class="col-md-3"></div>
        <div class="col-md-1 text-left"><%= f.label :title, '店舗名' %></div>
        <div class="col-md-8"><%= @post.sauna.sauna_name %></div>
        <%= f.hidden_field :sauna_id, :value => params[:id] %>
      </div>
    <% end %>

    <div class="form_group row">
      <div class="col-md-3"></div>
      <div class="col-md-1"></div>
      <div class="col-md-4"><%= image_tag @post.sauna.image, size: '200x250', class:"card-img-top" %></div>
    </div>

    <div class="m-2"></div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">評価</div>
      <div class="col-md-8"><%= render "static_rate", post: @post %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :title, 'タイトル' %></div>
      <div class="col-md-8"><%= f.text_field :title, placeholder: "タイトル", required: true, size: "43" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :body, 'レビュー' %></div>
      <div class="col-md-8"><%= f.text_area :body, placeholder: "感想を記入", required: true, size: "46x10" %></div>
    </div>


    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-2 text-left">表示ステータス</div>
      <div class="col-md-3">
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted, '表示　' %>

        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted, '非表示　' %>
      </div>
    </div>


    <div class="row">
      <div class="action center-block mx-auto">
      <%= f.submit '変更する', class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<div class='container px-5 px-sm-0'>
  <h4>投稿一覧</h4>
  <div class='row'>
  <div class="col-12 d-flex flex-column">
    <div class="d-flex flex-row flex-wrap">
      <%= render 'from', posts: @posts %>
    </div>
  </div>
  </div>
</div>
<div class="row">
  <div class="col-md-5"></div>
  <div class="col-md-2 mx-auto text-left">
    <%= paginate @posts %>
  </div>
  <div class="col-md-5"></div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">
    <div class="col-md-2"></div>
    <h4 class="col-md-2 mx-auto text-center">
      <strong>投稿詳細</strong>
    </h4>

    <div class="col-md-8"></div>
  </div>

  <div class="m-md-2"><br></div>

  <%= form_with model: @post, url: posts_path do |f| %>

  　<div class="form_group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">投稿者</div>
      <div class="col-md-8"><%= link_to admin_customer_path(@post.customer.id) do %><%= @post.customer.name %><% end %></div>
    </div>

    <div class="m-2"></div>

    <div class="form_group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">都道府県</div>
      <div class="col-md-8"><%= @post.sauna.prefecture %></div>
    </div>

    <div class="m-2"></div>

    <% if params[:id].present? %>
      <div class="form_group row">
        <div class="col-md-3"></div>
        <div class="col-md-1 text-left"><%= f.label :title, '店舗名' %></div>
        <div class="col-md-8"><%= @post.sauna.sauna_name %></div>
        <%= f.hidden_field :sauna_id, :value => params[:id] %>
      </div>
    <% end %>

    <div class="form_group row">
      <div class="col-md-3"></div>
      <div class="col-md-1"></div>
      <div class="col-md-4"><%= image_tag @post.sauna.image, size: '200x250', class:"card-img-top" %></div>
    </div>

    <div class="m-2"></div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left">評価</div>
      <div class="col-md-8"><%= render "static_rate", post: @post %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :title, 'タイトル' %></div>
      <div class="col-md-8"><%= @post.title %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :body, 'レビュー' %></div>
      <div class="col-md-8"><%= @post.body %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-2 text-left">表示ステータス</div>
      <div class="col-md-3">
        <% if @post.is_deleted == false %>
          <div class="text-success" >
            <%= '表示中' %>
          </div>
        <% else %>
          <div class="text-secondary" >
            <%= '非表示中' %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="action center-block mx-auto">
      <%= link_to '編集する',edit_admin_post_path(@post), class: 'btn btn-success' %>
      </div>
    </div>

  <% end %>

  <div class="form-group row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div id="comments_area_">
          <%= render "admin/post_comments/index", post_comments: @post_comments %>
        </div>
      </div>
    </div>
</div>