config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/top'
  end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    get 'saunas_bookmarks' => 'bookmarks#show'
    resources :posts
    resources :post_comments, only: [:create, :destroy]
    resources :saunas, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
    resources :customers, only: [:index,:show,:edit,:create,:update] do
      member do
        get :confirm
        patch :withdraw
      end
    end
  end

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :saunas
    resources :customers, except: [:new,:create,:destroy]
    resources :posts, only: [:index,:show,:edit,:update] do
      member do
        get :customer
        patch :withdraw
      end

      patch "hide/:comment_id" => "post_comments#hide", as: 'hide'
      patch "display/:comment_id" => "post_comments#display", as: 'display'
    end
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :post

  validates :comment, presence: true
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController

  def hide
    @comment = PostComment.find(params[:comment_id])
    @comment.update(is_deleted: true)
    redirect_to request.referer
  end

  def display
    PostComment.find_by(id: params[:comment_id]).update(is_deleted: false)
    redirect_to admin_post_path(params[:post_id])
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment, :is_deleted)
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_index.html.erb
<table>
  <tbody>
      <% post_comments.each do |post_comment| %>
      <tr>
        <td>
          <%= link_to customer_path(post_comment.customer) do %>
            <%= image_tag post_comment.customer.get_profile_image, size: "80x80" %><br>
            <%= post_comment.customer.name %>
          <% end %>
        </td>
        <td><%= post_comment.comment %></td>
        <td>
          <% if post_comment.is_deleted == false %>
            <%= link_to "非表示にする", admin_post_hide_path(post_comment.post,post_comment), method: :patch, class: "btn btn-outline-danger btn-sm", remote: true %>
          <% else %>
            <%= link_to "表示する", admin_post_display_path(post_comment.post,post_comment), method: :patch, class: "btn btn-outline-success btn-sm", remote: true %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>