config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/top'
  end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    get 'saunas_bookmarks' => 'bookmarks#show'
    resources :posts
    resources :post_comments, only: [:create, :destroy]
    resources :saunas, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
    resources :customers, only: [:index,:show,:edit,:create,:update] do
      member do
        get :confirm
        patch :withdraw
      end
    end
  end

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :saunas
    resources :customers, except: [:new,:create,:destroy]
    resources :posts, only: [:index,:show,:edit,:update] do
      member do
        get :customer
        patch :withdraw
      end

      patch "hide/:comment_id" => "post_comments#hide", as: 'hide'
      patch "display/:comment_id" => "post_comments#display", as: 'display'
    end
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
    <div class="container">
      <a class="navbar-brand" href="/admin"><span>極上サウナ</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <div class="d-flex flex-column">
            <div class="d-flex flex-row">
            <li>
            </li>
            <li>
              <%=  link_to admin_customers_path,class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> 会員一覧
              <% end %>
            </li>
            <li>
              <%=  link_to admin_saunas_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-bacon"></i> サウナ一覧
              <% end %>
            </li>
            <li>
              <%= link_to admin_posts_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> 投稿一覧
              <% end %>
            </li>
            <li>
              <%=  link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
            </div>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>©Gokujo Sauna</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
    <div class="container">
      <a class="navbar-brand" href="/"><span>極上サウナ</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <div class="d-flex flex-column">
            <div class="d-flex flex-row">
              <li>
                <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i> 新規登録
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>
            </div>
          </div>
        </ul>
      </div>
    </div>
  </nav>

</header>

app/views/layouts/_public_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
    <div class="container">
      <a class="navbar-brand" href="/"><span>極上サウナ</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <% if customer_signed_in? %>
        <h6 class="text-light ml-auto">ようこそ、<%= current_customer.name %>さん！</h6>
      <% end %>
        <ul class="navbar-nav ml-auto">
          <div class="d-flex flex-column">
            <div class="d-flex flex-row">
            <li>
              <%= link_to customer_path(current_customer),class: 'nav-link text-light' do %>
                <i class="fas fa-solid fa-user"></i> マイページ
              <% end %>
            </li>
            <li>
              <%= link_to customers_path,class: 'nav-link text-light' do %>
                <i class="fas fa-solid fa-users"></i> 会員一覧
              <% end %>
            </li>
            <li>
              <%= link_to saunas_path,class: 'nav-link text-light' do %>
                <i class="fas fa-bacon"></i> サウナ一覧
              <% end %>
            </li>
            <li>
              <%=  link_to posts_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> 投稿一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
            </div>
            <div>
              <li><%= render 'public/searches/search', class:'nav-link text-light' %></li>
            </div>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GokujoSauna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if customer_signed_in? %>
      <%= render 'layouts/public_header' %>
    <% elsif admin_signed_in? %>
      <%= render 'layouts/admin_header' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>